services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    environment:
      - PROD=true
    env_file: .env # MAKE SURE THIS FILE EXISTS
    restart: unless-stopped
