services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '3000'
    env_file: .prod.env # MAKE SURE THIS FILE EXISTS
    restart: unless-stopped
    networks:
      - opal-network

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '5180:80'
      - '5143:443'
      - '5143:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - opal-network

volumes:
  caddy_data:
  caddy_config:

networks:
  opal-network:
    driver: bridge
